/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wywxemdjojybfizcyvko"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5d3hlbWRqb2p5YmZpemN5dmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0ODM1NDEsImV4cCI6MjA4NTA1OTU0MX0.1-ZKZUQaRljTushgLkMPE-4lX0YhBDwSZRnNG1Ep2Zs"